//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyClientApplication3.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="cgeers.wordpress.com", ConfigurationName="ServiceReference.IWcfDataTypeService")]
    public interface IWcfDataTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="cgeers.wordpress.com/IWcfDataTypeService/GetEmployeesAsDictionary", ReplyAction="cgeers.wordpress.com/IWcfDataTypeService/GetEmployeesAsDictionaryResponse")]
        System.Collections.Generic.Dictionary<int, string> GetEmployeesAsDictionary();
        
        [System.ServiceModel.OperationContractAttribute(Action="cgeers.wordpress.com/IWcfDataTypeService/GetEmployeesAsCollection", ReplyAction="cgeers.wordpress.com/IWcfDataTypeService/GetEmployeesAsCollectionResponse")]
        System.Collections.ObjectModel.Collection<string> GetEmployeesAsCollection();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWcfDataTypeServiceChannel : ProxyClientApplication3.ServiceReference.IWcfDataTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WcfDataTypeServiceClient : System.ServiceModel.ClientBase<ProxyClientApplication3.ServiceReference.IWcfDataTypeService>, ProxyClientApplication3.ServiceReference.IWcfDataTypeService {
        
        public WcfDataTypeServiceClient() {
        }
        
        public WcfDataTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfDataTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfDataTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfDataTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetEmployeesAsDictionary() {
            return base.Channel.GetEmployeesAsDictionary();
        }
        
        public System.Collections.ObjectModel.Collection<string> GetEmployeesAsCollection() {
            return base.Channel.GetEmployeesAsCollection();
        }
    }
}
